apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acme-bookstore-product
spec:
  template:
    metadata:
      name: acme-bookstore-product-001
    spec:
      containers:
        - image: ivan2yk/acme-bookstore-product:7
          env:
            - name: DB_URL
              value: "."
            - name: DB_USERNAME
              value: "sa"
            - name: DB_PASSWORD
              value: "sa"
            - name: PROFILE
              value: "h2"